version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "python-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ttusrof85ugb"
s3_prefix = "python-test"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
profile = "personal"
confirm_changeset = true
